steps:

  - name: gcr.io/cloud-builders/bazel@sha256:7c34604572d4f001928b98f2b04e2feaebce67b7933e4182b817dcbfe9904bcd
    id: build
    args: ['--output_base=/workspace/build_output', 'build', ':tar-docker']

  - name: gcr.io/cloud-builders/bazel@sha256:7c34604572d4f001928b98f2b04e2feaebce67b7933e4182b817dcbfe9904bcd
    id: docker-archive
    args: ['--output_base=/workspace/build_output', 'cquery', '--output=files', ':tar-docker']
    waitFor: ['build']

  - name: quay.io/containers/skopeo:v1.16.1
    id: push-local
    entrypoint: '/bin/bash'
    args:
    - '-c'
    - |
      skopeo copy -f v2s2 --override-os="linux" --override-arch="amd64"  --digestfile /workspace/hash.txt --preserve-digests   docker-archive:bazel-out/k8-fastbuild/bin/tar-docker/tarball.tar docker-daemon:us-central1-docker.pkg.dev/$PROJECT_ID/repo1/test:server
    waitFor: ['build', 'docker-archive']

  - name: docker.io/busybox
    id: print-image-local
    entrypoint: '/bin/sh'
    args:
    - '-c'
    - |
      cat /workspace/hash.txt
    waitFor: ['push-local']

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/repo1/test:server

options:
  machineType: 'E2_HIGHCPU_32'
